### ISSUE TITLE
Incorrect TypeScript Type for `oldProps` in CustomComponent#applyProps

### ISSUE THREAD

**Issue by mutewinter** [pixijs/pixi-react#348]
### Description

`oldProps` is defined [here](https://github.com/inlet/react-pixi/blob/master/index.d.ts#L333) as `oldProps: Readonly<P>,`, however on first render it is an empty object. This can cause errors when attempting to access `oldProps` values on first render.

### Steps to reproduce

1. Create a custom component
2. Define `applyProps`
3. See invalid type for `oldProps`

### Additional info

- `@inlet/react-pixi` version: 6.8.0
- `React` version: 17
- `ReactDOM` version: 17
- `PIXI` version: 6

**Comment by inlet** [comment]
This is correctly, on initial render it doesn't have any old props on it.. we might set the type to something like `Readonly<P> | undefined`?

**Comment by mutewinter** [comment]
Currently it’s an empty object, which means it doesn’t throw when accessing one level deep props. But I agree with changing it to undefined is more clear. It would be a breaking change.
