### ISSUE TITLE
Error when using Stage

### ISSUE THREAD

**Issue by duckforce** [pixijs/pixi-react#352]
### Description

<img width="379" alt="image" src="https://user-images.githubusercontent.com/20500565/189744094-66f2fb25-989c-4f39-a851-d1af0613fe6d.png">

<img width="450" alt="image" src="https://user-images.githubusercontent.com/20500565/189744508-2bd8ef09-a167-4869-8026-95c49b738ecc.png">

### Steps to reproduce

1.  I just added Stage at any components and get error "Cannot set properties of undefined (setting 'autoStart')"
Maybe something wrong with webpack config or I should add special loader?

### Additional info

- `@inlet/react-pixi` version: 6.8.0
- `React` version: 17.0.2
- `ReactDOM` version: 17.0.2
- `PIXI` version: 6.5.3
- `webpack` version: 4.46.0

**Comment by saitonakamura** [comment]
@duckforce I'm puzzled and struggling to reproduce via codesandbox, https://codesandbox.io/s/angry-wave-1ly78t?file=/src/App.tsx. Can you provide a repro?

**Comment by duckforce** [comment]
I solve problem with removing hot-loader @pmmmwh/react-refresh-webpack-plugin.

Could you solve this problem?
@saitonakamura

**Comment by saitonakamura** [comment]
If you can provide a repro, we can look into it, but I'm not too well-versed in hot reload shenanigans to know how to approach it

**Comment by lunarraid** [comment]
Closing as no repro has been provided.
