### ISSUE TITLE
Library breaks with pixi.js v7

### ISSUE THREAD

**Issue by darwin67** [pixijs/pixi-react#355]
### Description
The library seems to be completely broken from pixi.js v7.

![error](https://user-images.githubusercontent.com/5746693/203436613-dee6f8f5-e27d-4775-8ac4-ec7c0997e30e.png)

### Steps to reproduce

1. Create a new react-app with latest pixi and react-pixi
2. Follow https://reactpixi.org/#usage and try mounting a pixi application with `Stage`

Error should show.

### Additional info

- `@inlet/react-pixi` version: 6.8
- `React` version: 17
- `ReactDOM` version: 17
- `PIXI` version: 7.0.4

**Comment by gitakileus** [comment]
There is same error on my side.
Please let me know how to solve this error

**Comment by michaelschufi** [comment]
Apparently, there's been some news regarding this project.

> ## News!
> 
> **ReactPixi will be a first-party React layer for PIXI and maintained by the core devs of PIXI!**
> 
> Dear ReactPixi community,
> 
> I am thrilled to announce that ReactPixi, the premier library for using Pixi.js with React, is being officially transferred to the Pixi team! This project started as a passion of mine, and it quickly grew into a beloved resource for the Pixi community thanks to all of your support.
> We are excited to be working closely with the team at Pixi, to continue improving and supporting the library. We want to extend a huge thank you to everyone who has supported ReactPixi over the years, and we especially want to thank Mat Groves for making this transfer possible.
> We can't wait to see what the future holds for the library under the stewardship of the Pixi team. Stay tuned for updates and new developments as we work together to take ReactPixi to the next level!
> 
> Sincerely,
> Patrick Brouwer

See https://github.com/pixijs/pixi-react/commit/99ce714981584928e0ae9e3e30f5e9d451c7c10b and the Readme.

Also, some of the work has already been started (e.g. React 18) if you check the recent commits of the repository.

So, I'm excited about the future and hope we will have support for PIXI v7 soon! 🤞

**Comment by baseten** [comment]
Hey guys, resolving any issues with PIXI v7 is my next priority after getting React 18 and docs updates completed

**Comment by SrBrahma** [comment]
Anxious to have React 18 & Pixi 7 support!
