### ISSUE TITLE
unable to resolve dependency tree

### ISSUE THREAD

**Issue by linediconsine** [pixijs/pixi-react#357]
### Description
I see errors while try to install this library

### Steps to reproduce

1.  npx create-react-app app --template typescript
2. npm install @inlet/react-pixi --save

### Additional info

- node -v   : v17.4.0
-   "@inlet/react-pixi": "^6.8.0",
-  "react": "^18.2.0",
-   "react-dom": "^18.2.0",
-  "pixi.js": "^7.0.5",

``` ✗ npm install @inlet/react-pixi --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: tree@0.1.0
npm ERR! Found: pixi.js@7.0.5
npm ERR! node_modules/pixi.js
npm ERR!   pixi.js@"^7.0.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer pixi.js@"^6.0.0" from @inlet/react-pixi@6.8.0
npm ERR! node_modules/@inlet/react-pixi
npm ERR!   @inlet/react-pixi@"^6.8.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/linediconsine/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/linediconsine/.npm/_logs/2022-12-18T18_34_23_750Z-debug-0.log ```

**Comment by caseymilne** [comment]
I just found the same issue today. I'm going to guess it requires an older version of React than 18.2.0? On StackOverflow a suggested work-around for similar issues (with other packages) is to use the flag --force. I tried it and the install went ahead, but it led to a lot of audit errors and I'm not sure if it will actually work (use at own risk, it might break your project).

**Comment by spassvogel** [comment]
fixed in https://github.com/pixijs/pixi-react/commit/29e19690d9ba0a8e435ba0c164e8b77ca286f61e, but you have to `npm i @pixi/react-pixi`

**Comment by baseten** [comment]
Yes this was a peer-deps issue in that `@inlet/react-pixi` did not support React 18, please use `@pixi/react-pixi` to resolve (and report any issues if you find them as we're still in `alpha`!) 😄
