### ISSUE TITLE
Quick Start doesn't work

### ISSUE THREAD

**Issue by tansanDOTeth** [pixijs/pixi-react#369]
The code shared in the README under Quick Start doesn't work. I would make a PR, but this is my first time using Pixi and I am unfamiliar with the APIs. I tried searching to find examples of the filters, but didn't see any in the tests for the `Text` component.

```
import { Stage, Container, Sprite } from '@inlet/react-pixi'

export const MyComponent = () => (
  <Stage>
    <Sprite image="./my-image.png" x={100} y={100} />

    <Container x={500}>
      <Text text="Hello World" filter={[blurFilter]} />
    </Container>
  </Stage>
)
```

**Comment by tansanDOTeth** [comment]
There is that issue too, but I was mostly referencing the `blurFilter` and the image using a src that is inaccessible.

**Comment by baseten** [comment]
Ah indeed, that's not a great example! I'll get that resolved as I update the docs over the coming days
