### ISSUE TITLE
Bug:  useApp () not working

### ISSUE THREAD

**Issue by josegamboa** [pixijs/pixi-react#410]
### Current Behavior

Hi,

I am trying to use `useApp ()` hook, but it is throwing up an exception, not sure if I am using it right,  just checked the documentation below:

https://reactpixi.org/hooks#useapp

invariant.js:24 Uncaught Invariant Violation: No Context found with `PIXI.Application`. Make sure to wrap component with `AppProvider`
    at invariant (http://localhost:3004/static/js/bundle.js:484:15)
    at useApp (http://localhost:3004/static/js/bundle.js:21143:3)
    at MyComponent (http://localhost:3004/static/js/bundle.js:115:66)
    at renderWithHooks (http://localhost:3004/static/js/bundle.js:44313:22)
    at mountIndeterminateComponent (http://localhost:3004/static/js/bundle.js:47599:17)
    at beginWork (http://localhost:3004/static/js/bundle.js:48895:20)
    at HTMLUnknownElement.callCallback (http://localhost:3004/static/js/bundle.js:33905:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3004/static/js/bundle.js:33949:20)
    at invokeGuardedCallback (http://localhost:3004/static/js/bundle.js:34006:35)
    at beginWork$1 (http://localhost:3004/static/js/bundle.js:53880:11)
`

### Expected Behavior

Use app constant to access the application

### Steps to Reproduce

Execute next chunk of code:
`
import { BlurFilter } from 'pixi.js';
import { Stage, Container, Sprite, Text, useApp } from '@pixi/react';
import { useMemo } from 'react';

 const MyComponent = () =>
{
  const blurFilter = useMemo(() => new BlurFilter(4), []);
  const app  = useApp ();

  return (
    <Stage>
      <Sprite
        image="https://pixijs.io/pixi-react/img/bunny.png"
        x={400}
        y={270}
        anchor={{ x: 0.5, y: 0.5 }}
      />

      <Container x={400} y={330}>
        <Text text="Hello World" anchor={{ x: 0.5, y: 0.5 }} filters={[blurFilter]} />
      </Container>
    </Stage>
  );
};

export  default MyComponent;`

`

### Environment

- **`@pixi/react` version**: *7.0.1*
- **`pixi.js` version**: *7.1.0*
- **`React` version**: *18.0.0*
- **`ReactDOM` version**: *18.0.0*
- **Browser & Version**: * Chrome*

**Comment by AndreasWintherMoen** [comment]
`useApp` is a hook which must be called inside an `AppProvider`. You can either create this yourself, or use the default one provided through the Stage component. This means you need a Stage component around MyComponent.

**Comment by josegamboa** [comment]
@AndreasWintherMoen , thanks a lot for helping with it.

Yep, I was missing the App provider in App.tsx:

`
import React, { useEffect, useRef } from 'react';
import * as PIXI from 'pixi.js';
import ReactPixi, { PixiRef, useTick, useApp, AppProvider } from '@pixi/react';
import GameBoard from './components/Board/Game';

const pixiApp = new PIXI.Application({});

function App() {
  return (
        <AppProvider value={pixiApp}>
          <GameBoard />
        </AppProvider>
  );
}

export default App;

`

**Comment by josegamboa** [comment]
Probably this is an opportunity to improve documentation.
