### ISSUE TITLE
Feature Request: the @inlet/react-pixi package should be taken down or the docs amended to note it's deprecated

### ISSUE THREAD

**Issue by fergusmeiklejohn** [pixijs/pixi-react#411]
### Description

Searching for pixiJS and react lead me to  @inlet/react-pixi. It would be better for new users to be directed more forcefully towards this repo IMO. I lost an hour or two trying to figure out why it wouldn't work I'm assuming React18.. :-(

Maybe this npm page could be amended: https://www.npmjs.com/package/@inlet/react-pixi
And the docs page here: https://reactpixi.org, where the install instruction is `npm install @inlet/react-pixi --save`

**Comment by AndreasWintherMoen** [comment]
Wow, I just had the exact same problem. Wasted an hour working with the wrong package.

**Comment by altarrok** [comment]
Wasted 2 hours downgrading all of my dependencies for this..

**Comment by Heilemann** [comment]
Same.

**Comment by patrikkaura** [comment]
Well I am glad that I found this issue ... after 30 minutes of trying I almost started to look for an alternative 😄

**Comment by sergioisidoro** [comment]
+1 - Was following https://reactpixi.org/ thinking it was the official docs

**Comment by RJWadley** [comment]
@inlet I believe you can help with this, since you own that older package.

I'd recommend deprecating the package by running `npm deprecate @inlet/react-pixi "package moved to @pixi/react"`
This will leave old versions accessible, but will show a warning when installing the package and on the npm page.

**Comment by inlet** [comment]
Good point guys! Sorry to hear it wasted your valuable time.

I’ll deprecate the package with a good deprecation message and bring down reactpixi.org asap

**Comment by inlet** [comment]
I've just deprecated the npm package `@inlet/react-pixi` and removed the `reactpixi.org` site as this is no longer needed.
