### ISSUE TITLE
Feature Request: Is It possible to change PIXI application to a custom one for compatibility

### ISSUE THREAD

**Issue by mathedu4all** [pixijs/pixi-react#425]
### Description

Since in wechat browser(a chinese chatting app), do not provide full features like web browser. so there is a lot of trial of using pixi.js in wechat, 

https://github.com/pixijs/pixijs/issues/5459

https://github.com/skyfish-qc/pixi-miniprogram

Is it possible to use pixi-react with a customized PIXI global variable provided?

**Comment by baseten** [comment]
Hey @mathedu4all you could do a couple of things here. 

1) Don't use `Stage` but use the custom render method into a `Container` of your own custom Application: https://pixijs.io/pixi-react/render/#custom-render-call
2) Create your own `Stage` component by forking the existing one and replace the `PIXI.Application` with whatever you need
