### ISSUE TITLE
Bug: Cannot use canvas renderer

### ISSUE THREAD

**Issue by salojoo** [pixijs/pixi-react#426]
### Current Behavior

Cannot use canvas with legacy pixi package.

1. First error is `Unable to auto-detect a suitable renderer.`. This can be fixed with `import "@pixi/canvas-renderer"; `
2. But there is a follow up error `this.app.renderer.context.extensions is undefined`

### Expected Behavior

Should render with canvas using `forceCanvas` option. 

### Steps to Reproduce

https://codesandbox.io/s/heuristic-booth-0pzgbk

### Environment

- **`@pixi/react` version**: *7.0.2*
- **`pixi.js-legacy` version**: *7.1.4*
- **`React` version**: *18.2.0*
- **`ReactDOM` version**: *18.2.0*
- **Browser & Version**: *Firefox/Chrome*
- **OS & Version**: *OS X 13.1*
- **Running Example**: *https://codesandbox.io/s/heuristic-booth-0pzgbk*

**Comment by baseten** [comment]
@Zyie I remember that we had this working, I'm wondering if it's related to non-legacy packages being `peerDependencies` of `@pixi/react`? 

I'm considering whether we should nuke all pixi packages from `peerDependencies` and just explicit instruct users to install it alongside pixi-react?

**Comment by Zyie** [comment]
> @Zyie I remember that we had this working, I'm wondering if it's related to non-legacy packages being `peerDependencies` of `@pixi/react`?
> 
> I'm considering whether we should nuke all pixi packages from `peerDependencies` and just explicit instruct users to install it alongside pixi-react?

I don't think that is the issue

The pixi legacy packages are just mixins for the normal pixi packages so as long as they are installed and imported then it should work. 

`pixi.js-legacy` will import these mixins so as long as `import 'pixi.js-legacy'` is called within the project everything should work

Also for this example Filters do not work in pixi-legacy which may be why it is not working

**Comment by salojoo** [comment]
I removed the filtering, but the error still persist

**Comment by salojoo** [comment]
Tried updating to pixi.js 7.2.0, but no luck. Adding `import 'pixi.js-legacy'` doesn't help either

**Comment by Zyie** [comment]
should be fixed in `7.1.0`!

thanks for the help @salojoo
