### ISSUE TITLE
Feature Request:  Migration guide from react-pixi-fiber

### ISSUE THREAD

**Issue by LukeWood** [pixijs/pixi-react#440]
### Description

it would be great to provide an "official" recommendation between react-pixi-fiber and @pixi/react!  I think they both look quite "official", and its confusing to someone who doesn't have a ton of context on the ecosystem!  

If this is the recommended package, a migration guide would be wonderful!  I'm happy to contribute as well.

**Comment by LukeWood** [comment]
In particular, is there an equivalent to CustomPIXIComponent?

**Comment by michalochman** [comment]
There is a similar API, see: https://pixijs.io/pixi-react/custom-component/

You can expect it to work more or less the same, but you need to change the behaviour method names.

**Comment by LukeWood** [comment]
I went through the process today and it was mostly flawless.  The type annotations are nuancedly different due to inference but great job on the new API.  I prefer it

**Comment by LukeWood** [comment]
But my original question still stands!  Does the Pixi team recommend @pixi/react at this time over react Pixi fiber?
