### ISSUE TITLE
Bug: interactive does not exist

### ISSUE THREAD

**Issue by y0unghe** [pixijs/pixi-react#456]
### Current Behavior

I am trying to add a click event to `Sprite`, but I am getting:

```
Type '{ children: never[]; interactive: boolean; position: { x: number; y: number; }; width: number; height: number; image: string; pointerdown: () => void; }' is not assignable to type 'IntrinsicAttributes & Partial<Omit<Sprite, P | ReadonlyKeys<Sprite> | keyof WithSource> & WithPointLike<P>> & WithSource & InteractionEvents & { ...; } & { ...; }'.
  Property 'interactive' does not exist on type 'IntrinsicAttributes & Partial<Omit<Sprite, P | ReadonlyKeys<Sprite> | keyof WithSource> & WithPointLike<P>> & WithSource & InteractionEvents & { ...; } & { ...; }'.ts(2322)
```

### Expected Behavior

Should be able to set the `interactive` to `true`

### Steps to Reproduce

Add the package to create-react-app

```
    "@pixi/react": "^7.1.1",
```

### Environment

- **`@pixi/react` version**: *7.1.1*
- **`pixi.js` version**: *e.g. 7.1.1*
- **`React` version**: *18.2.0*
- **`ReactDOM` version**: *18.2.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Mac *

**Comment by augusttty** [comment]
In your tsconfig.json, add `"esModuleInterop": true,` into  compilerOptions

**Comment by Zyie** [comment]
let me know if the above does not work and i will reopen the issue
