### ISSUE TITLE
Bug: Component and child components not being destroyed on unmount by default

### ISSUE THREAD

**Issue by avpeery** [pixijs/pixi-react#466]
### Current Behavior

According to the docs, it is my understanding that we shouldn't have to handle cleaning up components by destroying on unmount: [https://pixijs.io/pixi-react/custom-component/#api](https://pixijs.io/pixi-react/custom-component/#api)
However, I found that it actually produces a memory leak unless I specifically do something like 
```
willUnmount: (countainer) => {
      container.destory({children: true}) 
}
```

### Expected Behavior

Expected not to have to handle clean up of my components (custom and plain components built into pixi/react)

### Steps to Reproduce

Will provide a jsbin or codepen when I have time, but essentially making a container component without setting up clean up (including clean up of children) produces a memory leak

### Environment

- **`@pixi/react` version**: *e.g. 7.0.0*
- **`pixi.js` version**: *e.g. 7.1.0*
- **`React` version**: *e.g. 18.0.0*
- **`ReactDOM` version**: *e.g. 18.0.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by nosleepdemon** [comment]
Hey @avpeery , I saw you closed this but I suspect I am encountering a similar issue. Did you implement your own cleanup method, or is there a proper method available now? I've found the pixi-react documentation to be a bit sparse, but I'm also new to react.

**Comment by avpeery** [comment]
@nosleepdemon I am no longer using pixi react, so unfortunately not sure or remember what the solution was here. We are just using pixi directly.

**Comment by nosleepdemon** [comment]
> [@nosleepdemon](https://github.com/nosleepdemon) I am no longer using pixi react, so unfortunately not sure or remember what the solution was here. We are just using pixi directly.

Ah, no problem. I am also tempted to switch back to using pixi directly, thanks for the fast reply.
