### ISSUE TITLE
Bug: Peer Dependency of pixi.js breaks any app <7.2

### ISSUE THREAD

**Issue by robodove** [pixijs/pixi-react#467]
### Current Behavior

Everything was working until pixi.js released v7.3.3 yesterday

Now our production build fails, local builds fail

### Expected Behavior

Well existing packages shouldn't be affected!

### Steps to Reproduce

So far haven't been able to pin it down, but we get the error of 

Can't redeclare "SORTABLE_CHILDREN";

### Environment

- **`@pixi/react` version**: * 7.0.2*
- **`pixi.js` version**: *7.1.2*
- **`React` version**: *18x*
- **`ReactDOM` version**: *18x*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

### Possible Solution

Well, maybe pin the peer dep <= 7.3.3 ?

**Comment by Zyie** [comment]
Hi, i can't reproduce this

If you can provide me with an example i will reopen and look into this!

**Comment by robodove** [comment]
In any case, why would it make sense to not pin exact versions of PixiJS peer dependency?

**Comment by Zyie** [comment]
this project should work for any pixi v6/7 version, so it shouldn't need to be pinned to a specific version, just a major version which `>=6.0.0` should cover
