### ISSUE TITLE
Bug: unable to see "Hello world" text from readme example?

### ISSUE THREAD

**Issue by cmdcolin** [pixijs/pixi-react#474]
### Current Behavior

renders the bunny but not the hello world(?)

### Expected Behavior

renders the hello world

### Steps to Reproduce

copy from readme
running example on stackblitz https://stackblitz.com/edit/vitejs-vite-8xdhfy?file=src%2FApp.tsx

### Environment

  pixi.js@"^7.4.0"
  @pixi/react@"^7.1.1"
react@18.2.0
react-dom@18.2.0 project
firefox 122.0.1 snap
ubuntu 23 

### Additional Information

console log with hello:true
PixiJS 7.4.0 - WebGL 2 - https://pixijs.com

screenshot
![image](https://github.com/pixijs/pixi-react/assets/6511937/125a9aac-3551-486c-8959-862daa528b18)

**Comment by cmdcolin** [comment]
i am only asking cause the code sample has code like

```

      <Container x={200} y={230}>
        <Text
          text="Hello World"
          anchor={{ x: 0.5, y: 0.5 }}
          filters={[blurFilter]}
        />
      </Container>
```
note: new to pixi :) just looking about

**Comment by zOadT** [comment]
Yeah, its just that we render black text on a black background here 😄 Changing the color makes it visible
```js
import { BlurFilter, TextStyle } from 'pixi.js'; // add TextStyle import
// [...]
      <Container x={200} y={230}>
        <Text
          text="Hello World"
          anchor={{ x: 0.5, y: 0.5 }}
          filters={[blurFilter]}
          style={new TextStyle({
            fill: ['#ffffff'],
          })}
        />
      </Container>
```
