### ISSUE TITLE
Feature Request: Isometric Tileset / Tilemap ?

### ISSUE THREAD

**Issue by jktan0504** [pixijs/pixi-react#489]
### Description

Hi experts..
This is really a great library. However, any docs or solution to do or integrate with isometric tileset / tilemap with this react-pixi ? Please share me some knowledge.

Thanks

**Comment by trezy** [comment]
I'm closing this since it's not a Pixi React issue, but we can probably help you out on the [Official Pixi.js Discord](https://discord.com/invite/CPTjeb28nH).
