### ISSUE TITLE
Bug: useTick not ticking on initial load during `vite dev`

### ISSUE THREAD

**Issue by IanSSenne** [pixijs/pixi-react#506]
### Current Behavior

on the initial load during `vite dev` the ticker does not start automatically.

### Expected Behavior

I expect the ticker to automatically start.

### Steps to Reproduce

1. download [bug-sample.zip](https://github.com/user-attachments/files/16386632/bug-sample.zip)
2. install dependencies (I use yarn@1)
3. yarn dev
4. observe ticker not counting.
5. change App.tsx
6. observe ticker counting after hmr.

### Environment

| Item | Version |
| ----- | ------ |
| Google Chrome | 126.0.6478.183 (Official Build) (64-bit) (cohort: Control) |
| OS | Windows 11 Version 22H2 (Build 22621.3880) |
| JavaScript | V8 12.6.228.28 |
| ReactDOM | ^18.3.1 |
| React         | ^18.3.1 |
| pixi.js | 8 (8.2.5) |
| @pixi/react | 8.0.0-beta.2 |

### Additional Information

from a little bit of investigation it seems that the app.ticker is undefined when the hook runs for the first time.

**Comment by trezy** [comment]
Hey @IanSSenne, can you try the `8.0.0-beta.3` release and verify that it resolves your issue?

**Comment by IanSSenne** [comment]
hi @trezy I have reproduced the issue on the template above using `8.0.0-beta.3`

**Comment by IanSSenne** [comment]
if your unable to reproduce it using the template please let me know.

**Comment by trezy** [comment]
All right @IanSSenne, check it out! I loaded up your sample code, updated to `beta.4`, and confirmed that I no longer see the issue. If you could take a look and verify, I'd appreciate it! I'll close out the issue once I have confirmation it's fixed. 😁

**Comment by IanSSenne** [comment]
seems to work on my end.
