### ISSUE TITLE
Bug: events on a Sprite don't work on initial run using Vite

### ISSUE THREAD

**Issue by francollamas** [pixijs/pixi-react#520]
### Current Behavior

When I create a sprite and add an onPointerDown property that changes the tint property of the sprite, it doesn't work on initial `pnpm run dev`, but it works after changing anything in the file and saving it (after an HMR)

### Expected Behavior

I expect that after running the project with `pnpm run dev`, when I click the sprite it should change it's color.

### Steps to Reproduce

1. Open [live example](https://stackblitz.com/edit/vitejs-vite-gwjxkm?file=src%2FApp.jsx) on Stackblitz.
2. Wait until it shows the bunny on the preview tab.
3. Try to click the bunny and nothing happens.
4. Edit the `App.jsx` file (it could be adding blank line) and let HMR acts.
5. Try to click the bunny and now it works, the bunny change it's color successfully.

### Environment

- **`@pixi/react` version**: *8.0.0-beta.7*
- **`pixi.js` version**: *8.2.6*
- **`React` version**: *18.3.1*
- **`ReactDOM` version**: *18.3.1*
- **Browser & Version**: *126.0.6478.183 (Official Build) (x86_64)*
- **OS & Version**: *MacOS Sonoma 14.5*
- **Running Example**: *[example on Stackblitz](https://stackblitz.com/edit/vitejs-vite-gwjxkm?file=src%2FApp.jsx)*

### Additional Information

I don't know if it's also happening with another pixi components.
But I could see that if i move the `onPointerDown` and `eventMode` properties to the `<container>` tag, it's working like expected!

**Comment by itsezc** [comment]
This same exists when using a combination of React and Valtio, initially I assumed it a problem on how I was managing my state.
