### ISSUE TITLE
Bug: Next.js 15 & React 19 incompatibility

### ISSUE THREAD

**Issue by thejustinwalsh** [pixijs/pixi-react#551]
### Current Behavior

Next.js 15 is using React 19.0.0-rc when you use the `app` folder, and all versions of `@pixi/react` are using internal api's that break in React 19.

See:
- https://github.com/vercel/next.js/issues/71836
- https://github.com/pmndrs/react-three-fiber/issues/3222

### Expected Behavior

@pixi/react v7 may need to it's peer dependencies updated to limit the range of react it is compatible with. i.e. 17-18
@pixi/react v8 should likely support React 18 & 19

### Steps to Reproduce

Create a @pixi/react app using Next.js 15 and use the app router.
`-or-`
Create a @pixi/react app using React 19.

### Environment

- **`@pixi/react` version**: *>=7.1.2*
- **`pixi.js` version**: *>=7.4.2*
- **`React` version**: *>=19.0.0-rc*
- **`ReactDOM` version**: *>=19.0.0-rc*

### Possible Solution

https://github.com/pmndrs/react-three-fiber/issues/3222#issuecomment-2294895318

### Additional Information

Temporary workaround: downgrade to `Next@^14.2.16`.

**Comment by trezy** [comment]
I've been dreading this. I'm not sure it's going to be possible to support both versions of React with a single version of the lib. This is deffo on my radar, tho.

**Comment by linonetwo** [comment]
Or limit to React 19, because React 19 is public now.

**Comment by Fatdrfrog** [comment]
Second workaround: use `pages` routing instead of `app`

**Comment by trezy** [comment]
This is fixed in [`@pixi/react@8.0.0-beta.17`](https://github.com/pixijs/pixi-react/releases/tag/v8.0.0-beta.17).
